# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KAuO1ZGaHb1jIvIjSgZCdn2UhHIo57gi
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('hypertension_dataset.csv')
df.head()

df.info()

df.shape

df.isnull().sum()

df = df.dropna(axis=1, thresh=0.7*len(df))   # drop columns with >30% nulls
df = df.fillna(df.mode().iloc[0])

#encoding the categorical data
le = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

cols=['Salt_Intake','Sleep_Duration','BMI']
df[cols]=df[cols].astype('int')

df.head()

X = df.drop(columns=['Has_Hypertension'])   # assuming 'hypertension' is target
y = df['Has_Hypertension']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- Decision Tree (Gini) ---
dt_gini = DecisionTreeClassifier(criterion="gini", max_depth=5, random_state=42)
dt_gini.fit(X_train, y_train)
y_pred_gini = dt_gini.predict(X_test)

# --- Decision Tree (Entropy) ---
dt_entropy = DecisionTreeClassifier(criterion="entropy", max_depth=5, random_state=42)
dt_entropy.fit(X_train, y_train)
y_pred_entropy = dt_entropy.predict(X_test)

#evalution
print("===== Gini Decision Tree =====")
print("Accuracy:", accuracy_score(y_test, y_pred_gini))
print(classification_report(y_test, y_pred_gini))

print("\n===== Entropy Decision Tree =====")
print("Accuracy:", accuracy_score(y_test, y_pred_entropy))
print(classification_report(y_test, y_pred_entropy))

# --- Confusion Matrices ---
fig, ax = plt.subplots(1,2, figsize=(12,5))

sns.heatmap(confusion_matrix(y_test, y_pred_gini), annot=True, fmt="d", cmap="Blues", ax=ax[0])
ax[0].set_title("Confusion Matrix (Gini)")

sns.heatmap(confusion_matrix(y_test, y_pred_entropy), annot=True, fmt="d", cmap="Greens", ax=ax[1])
ax[1].set_title("Confusion Matrix (Entropy)")

plt.show()

"""**Decission Tree**"""

dataset=pd.read_csv('hypertension_dataset.csv')
dataset.head()

# Encode categorical features in the 'dataset' DataFrame
le = LabelEncoder()
for col in dataset.select_dtypes(include=['object']).columns:
    dataset[col] = le.fit_transform(dataset[col])

dataset.dropna(axis=1, how='all',inplace=True)
dataset.fillna(dataset.mode().iloc[0], inplace=True)

x=dataset.drop(columns=['Has_Hypertension'])
y=dataset['Has_Hypertension']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Hyperparameter Tunning
param_grid={
    'max_depth':[3,5,10,None],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,5],
    'criterion':['gini','entropy']
}

grid=GridSearchCV(DecisionTreeClassifier(random_state=42),param_grid, cv=5, scoring='f1')
grid.fit(x_train,y_train)

print("Best params:",grid.best_params_)
print("Best score:",grid.best_score_)

#Train with best params
best_dt=grid.best_estimator_
y_pred=best_dt.predict(x_test)

#Evalution
print(" Test Accuracy:",accuracy_score(y_test,y_pred))
print("classification Report:\n", classification_report(y_test,y_pred))