# -*- coding: utf-8 -*-
"""LasooRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyKxnbP-Yd0NVFRK8ZmZWVCXWd2IvYVQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import warnings
warnings.filterwarnings('ignore')

dataset=pd.read_csv('data.csv')
dataset.head()

dataset.nunique()

dataset.shape

dataset.isnull().sum()

dataset=dataset.drop(['date','street','country'], axis=1)

dataset=dataset[dataset['price']>0]
dataset.shape
dataset.info()

cols=['bedrooms','bathrooms','floors']
dataset[cols]=dataset[cols].astype('int')

le=LabelEncoder()
dataset['city']=le.fit_transform(dataset['city'])
dataset['statezip']=le.fit_transform(dataset['statezip'])

dataset.head()

X = dataset.drop(columns=['price'])
y = dataset['price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#multi-LinearRegression
mlr = LinearRegression()
mlr.fit(X_train, y_train)
y_pred_mlr = mlr.predict(X_test)

#ridge Regression
ridge = Ridge()
ridge_cv = GridSearchCV(ridge, {'alpha':[0.1, 1, 10, 50, 100]}, cv=5, scoring='r2')
ridge_cv.fit(X_train, y_train)
best_ridge = ridge_cv.best_estimator_
y_pred_ridge = best_ridge.predict(X_test)

#lasso Regressionllasso = Lasso(max_iter=10000)
lasso=Lasso(max_iter=10000)
lasso_cv = GridSearchCV(lasso, {'alpha':[0.001, 0.01, 0.1, 1, 10]}, cv=5, scoring='r2')
lasso_cv.fit(X_train, y_train)
best_lasso = lasso_cv.best_estimator_
y_pred_lasso = best_lasso.predict(X_test)

def print_metrics(y_true, y_pred, model_name):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    print(f"\n📊 {model_name} Performance")
    print(f"R² Score : {r2:.3f}")
    print(f"MSE      : {mse:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"MAE      : {mae:.3f}")

# Print metrics for all models
print_metrics(y_test, y_pred_mlr, "Multilinear Regression")
print_metrics(y_test, y_pred_ridge, f"Ridge Regression (alpha={best_ridge.alpha})")
print_metrics(y_test, y_pred_lasso, f"Lasso Regression (alpha={best_lasso.alpha})")

plt.figure(figsize=(14,6))

# Ridge Plot
plt.subplot(1,2,1)
plt.scatter(y_test, y_pred_ridge, alpha=0.5, color="blue")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title(f"Ridge Regression (alpha={best_ridge.alpha})")

# Lasso Plot
plt.subplot(1,2,2)
plt.scatter(y_test, y_pred_lasso, alpha=0.5, color="green")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title(f"Lasso Regression (alpha={best_lasso.alpha})")

plt.tight_layout()
plt.show()