# -*- coding: utf-8 -*-
"""linearRegression1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwfkP0aKMQuF55-CLZDa0ZFfbLo_9H3L
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,mean_absolute_percentage_error, r2_score

df=pd.read_csv('data.csv')

df.shape

df.head(10)

df.notnull().sum()

# Convert 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Extract year, month, day from date
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

df.head()

# Select features and target
X = df[['sqft_living', 'year', 'month', 'day']]
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# evalution metrices
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mape=mean_absolute_percentage_error(y_test,y_pred)
r2_score=r2_score(y_test,y_pred)

print(f"mean square error:{mse}")
print(f"mean absolute error:{mae}")
print(f"mean absolute percentage error:{mape}")
print(f"r2 score:{r2_score}")

plt.scatter(X_test['sqft_living'], y_test, color='blue', label='Actual values')

# plotting for predicted values
plt.scatter(X_test['sqft_living'], y_pred, color='red', label='Predicted values')

plt.xlabel('sqft_living')
plt.ylabel('price')
plt.title('Actual vs Predicted Price')
plt.legend()
plt.show()