# -*- coding: utf-8 -*-
"""NavieaBayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZ3YSgzjOPWrwPUXvEJoLo9STtu6XDPH
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, accuracy_score
from sklearn.naive_bayes import GaussianNB

df=pd.read_csv('hypertension_dataset.csv')

df.isnull().sum()

df.head()

df.info()

df = df.dropna(axis=1, thresh=0.7*len(df))
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].mean())

# Encode categorical variables
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

# Split features and target
X = df.drop("Has_Hypertension", axis=1)
y = df["Has_Hypertension"]

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Naive Bayes Classifier (Gaussian)
nb = GaussianNB(var_smoothing=1e-9)
nb.fit(X_train, y_train)

y_pred = nb.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))